/*
 * @Description:
 * @Author: Sunly
 * @Date: 2023-11-22 14:17:33
 */
import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

import type { ICrawlerParams } from "./api/crawlee-data";

const inter = Inter({ subsets: ["latin"] });

const handleClick = () => {
  const params: ICrawlerParams = {
    target_url: "https://www.baidu.com",
    match_urls: ["https://www.baidu.com/**"],
    max_pages: 5,
    selector: "body",
  };

  fetch(
    `/api/crawlee-data?target_url=${params.target_url}&match_urls=${params.match_urls}&max_pages=${params.max_pages}&selector=${params.selector}`
  )
    .then((res) => res.json())
    .then((res) => console.log(res));
};

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <button onClick={handleClick}>TEST</button>
      </main>
    </>
  );
}
